# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slave_ip', models.CharField(max_length=200)),
                ('slave_hostname', models.CharField(max_length=200)),
                ('slave_location', models.CharField(max_length=200)),
            ],
        ),
    ]
