# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 08:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subordinates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subordinate',
            name='id',
        ),
        migrations.AlterField(
            model_name='subordinate',
            name='subordinate_ip',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
