# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-02 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ping_db',
            name='slave_hostname',
            field=models.CharField(default='HI', max_length=50),
        ),
    ]
